[project]
name = "economy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.12.4",
    "numpy>=2.3.2",
    "numpy-financial>=1.0.0",
    "pandas>=2.3.1",
    "typing>=3.10.0.0",
]
